FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma

RUN corepack enable && corepack prepare pnpm@9.15.0 --activate

RUN pnpm install

COPY . .

EXPOSE 3000

CMD ["pnpm", "dev:docker"]